### PR TITLE
folders are created with Form too now

### PR DESCRIPTION
**Pull request by aquib22co**
Form creation => Folder done
Materials dir removed

### CODE REVIEW

**Comment by aquib22co** [comment]
pls accept sar

**Comment by Zainfr** [comment]
E**S**C**A**L**A**T**I**O**N**!!!!!!!!

**Comment by aquib22co** [comment]
pls acept sar

**Comment by aquib22co** [comment]
pls sar

**Comment by Zainfr** [comment]
After careful consideration, we've decided to terminate your employment due to consistent poor performance and failure to adhere to our company's standards.

**Pull request merged**
